version: '3.8'

services:
  python-backend:
    build:
      context: ./backend-python/py
      dockerfile: Dockerfile
    container_name: safe-python-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend-python/py:/app
    environment:
      - PYTHONIOENCODING=utf-8
      - PYTHONPATH=/app/backend
    env_file:
      - ./backend-python/py/backend/.env
    restart: always
    networks:
      - safe-network

  redis:
    image: redis:7-alpine
    container_name: safe-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - safe-network

volumes:

  redis_data:

networks:
  safe-network:
    driver: bridge
